/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Vitor Henrique
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nomeusuario = new javax.swing.JLabel();
        enderecousuario = new javax.swing.JLabel();
        telefoneusuario = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        emailusuario = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadastroCliente.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 339, 390);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("     Cadastro Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 0, 270, 50);

        jTextField1.setForeground(new java.awt.Color(153, 0, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 90, 290, 20);

        nomeusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nomeusuario.setForeground(new java.awt.Color(102, 0, 102));
        nomeusuario.setText("Nome: *");
        getContentPane().add(nomeusuario);
        nomeusuario.setBounds(370, 70, 60, 18);

        enderecousuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        enderecousuario.setForeground(new java.awt.Color(102, 0, 102));
        enderecousuario.setText("Endereço: *");
        getContentPane().add(enderecousuario);
        enderecousuario.setBounds(370, 120, 90, 18);

        telefoneusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        telefoneusuario.setForeground(new java.awt.Color(102, 0, 102));
        telefoneusuario.setText("Telefone: *");
        getContentPane().add(telefoneusuario);
        telefoneusuario.setBounds(370, 170, 90, 18);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(370, 190, 290, 20);

        emailusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailusuario.setForeground(new java.awt.Color(102, 0, 102));
        emailusuario.setText("E-mail: *");
        getContentPane().add(emailusuario);
        emailusuario.setBounds(370, 220, 70, 18);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(370, 240, 290, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Senha: *");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 270, 70, 18);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(370, 140, 290, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(370, 290, 290, 20);

        jButton1.setBackground(new java.awt.Color(102, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Cadastrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 320, 110, 25);

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("Cancelar Cadastro");
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 320, 170, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailusuario;
    private javax.swing.JLabel enderecousuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel nomeusuario;
    private javax.swing.JLabel telefoneusuario;
    // End of variables declaration//GEN-END:variables
}
