/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.AdmDAO;
import Model.Adm;
import static View.CadastroUsuario.validar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vitor Henrique
 */
public class CadastroAdm extends javax.swing.JFrame {
 MaskFormatter mascaraTelefone;
    public void criarMascara(){
        try {
           mascaraTelefone = new MaskFormatter("(##)#####-####");
           mascaraTelefone.install(f_telefone);
        } catch(Exception ex){
            throw new RuntimeException(ex);
        }
    }
    /**
     * Creates new form CadastroAdm
     */
    public CadastroAdm() {
        initComponents();
        criarMascara();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        f_nome = new javax.swing.JTextField();
        nomeusuario = new javax.swing.JLabel();
        enderecousuario = new javax.swing.JLabel();
        telefoneusuario = new javax.swing.JLabel();
        emailusuario = new javax.swing.JLabel();
        f_email = new javax.swing.JTextField();
        f_endereco = new javax.swing.JTextField();
        jButtoncadastrousuario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        f_telefone = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        f_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadastroCliente.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Cadastro Administrador");

        f_nome.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        f_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nomeActionPerformed(evt);
            }
        });

        nomeusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nomeusuario.setForeground(new java.awt.Color(102, 0, 102));
        nomeusuario.setText("Nome: *");

        enderecousuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        enderecousuario.setForeground(new java.awt.Color(102, 0, 102));
        enderecousuario.setText("Endereço: *");

        telefoneusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        telefoneusuario.setForeground(new java.awt.Color(102, 0, 102));
        telefoneusuario.setText("Telefone: *");

        emailusuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        emailusuario.setForeground(new java.awt.Color(102, 0, 102));
        emailusuario.setText("E-mail: *");

        f_email.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N

        f_endereco.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N

        jButtoncadastrousuario.setBackground(new java.awt.Color(102, 0, 102));
        jButtoncadastrousuario.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButtoncadastrousuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncadastrousuario.setText("Cadastrar");
        jButtoncadastrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastrousuarioActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar Cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        f_telefone.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Senha: *");

        f_senha.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_email, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeusuario)
                                .addComponent(f_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enderecousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(f_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefoneusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(f_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtoncadastrousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel1)))
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(f_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(nomeusuario)
                            .addGap(2, 2, 2)
                            .addComponent(f_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(enderecousuario)
                            .addGap(2, 2, 2)
                            .addComponent(f_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(telefoneusuario)
                            .addGap(2, 2, 2)
                            .addComponent(f_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(emailusuario)
                            .addGap(112, 112, 112)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtoncadastrousuario)
                                .addComponent(jButton2))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nomeActionPerformed
    public boolean checaCampos(){
        if(f_nome.getText().length()>0 && f_endereco.getText().length()>0 
           && f_telefone.getText().length()>0 && String.valueOf(f_senha.getPassword()).length()>0) {
           if(validar(f_email.getText()) == false){
            JOptionPane.showMessageDialog(null, "Informe um e-mail válido!");
            return false;  
        } 
           return true;
        }
        return false;
        
    }
        public static boolean validar(String email)
    {
        boolean isEmailIdValid = false;
        if (email != null && email.length() > 0) {
            String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
            Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(email);
            if (matcher.matches()) {
                isEmailIdValid = true;
            }
        }
        return isEmailIdValid;
    }
    private void jButtoncadastrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastrousuarioActionPerformed
        
        if(checaCampos() == true){
            Adm m = new Adm();
            m.setNome(f_nome.getText());
            m.setEndereco(f_endereco.getText());
            m.setTelefone(f_telefone.getText());
            m.setEmail(f_email.getText());
            m.setSenha(String.valueOf(f_senha.getPassword()));
            AdmDAO admDAO = new AdmDAO();
            admDAO.create(m);
   
            setVisible(false);
        }else {
           JOptionPane.showMessageDialog(null, "Há campos não preenchidos");
        }
            
    }//GEN-LAST:event_jButtoncadastrousuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailusuario;
    private javax.swing.JLabel enderecousuario;
    private javax.swing.JTextField f_email;
    private javax.swing.JTextField f_endereco;
    private javax.swing.JTextField f_nome;
    private javax.swing.JPasswordField f_senha;
    private javax.swing.JFormattedTextField f_telefone;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtoncadastrousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nomeusuario;
    private javax.swing.JLabel telefoneusuario;
    // End of variables declaration//GEN-END:variables

 
}
