/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Vitor Henrique
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cadastarusuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        loginusuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cadastraradm = new javax.swing.JButton();
        loginadm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Bem-Vindo ao Register Pet");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, -30, 460, 120);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("É novo por aqui?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 100, 190, 30);

        cadastarusuario.setBackground(new java.awt.Color(102, 0, 102));
        cadastarusuario.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        cadastarusuario.setForeground(new java.awt.Color(102, 0, 102));
        cadastarusuario.setText("Cadastrar");
        cadastarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastarusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cadastarusuario);
        cadastarusuario.setBounds(120, 150, 110, 25);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Já é de casa?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 210, 180, 20);

        loginusuario.setBackground(new java.awt.Color(102, 0, 102));
        loginusuario.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        loginusuario.setForeground(new java.awt.Color(102, 0, 102));
        loginusuario.setText("Login");
        loginusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(loginusuario);
        loginusuario.setBounds(130, 260, 80, 25);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("É administrador?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 100, 200, 26);

        cadastraradm.setBackground(new java.awt.Color(102, 0, 102));
        cadastraradm.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        cadastraradm.setForeground(new java.awt.Color(102, 0, 102));
        cadastraradm.setText("Cadastrar");
        getContentPane().add(cadastraradm);
        cadastraradm.setBounds(410, 150, 100, 25);

        loginadm.setBackground(new java.awt.Color(102, 0, 102));
        loginadm.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        loginadm.setForeground(new java.awt.Color(102, 0, 102));
        loginadm.setText("Login");
        loginadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginadmActionPerformed(evt);
            }
        });
        getContentPane().add(loginadm);
        loginadm.setBounds(420, 260, 73, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaInicial.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 0, 650, 380);

        setSize(new java.awt.Dimension(681, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastarusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastarusuarioActionPerformed

    private void loginusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginusuarioActionPerformed

    private void loginadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginadmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginadmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastarusuario;
    private javax.swing.JButton cadastraradm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginadm;
    private javax.swing.JButton loginusuario;
    // End of variables declaration//GEN-END:variables
}
